pipeline {
    agent any
    stages {
        stage('User Input') {
            steps {
                script {
                    
                    //for user input
                    def userInput = input(
                        id: 'userInput', 
                        message: 'Please provide user information:',
                        parameters: [
                            string(name: 'First Name', description: 'Your first name:'),
                            string(name: 'Last Name', description: 'Your last name:'),
                            string(name: 'Age', description: 'Your age:')
                            
                        ]
                    )
                    
                    // variable defining
                    def firstName = userInput['First Name']
                    def lastName = userInput['Last Name']
                    def age = userInput['Age']
                    
                    
                    //to display user input
                    echo "First Name: ${firstName}"
                    echo "Last Name: ${lastName}"
                    echo "Age: ${age}"
                }
            }
        }
    }
}
